services:
  agent_service:
    build:
      context: .
      dockerfile: docker/Dockerfile.service
    ports:
      - "80:80"
    env_file:
      - .env

  streamlit_app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - "8501:8501"
    depends_on:
      - agent_service
    environment:
      - AGENT_URL=http://agent_service

  base_db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    container_name: base_db
    ports:
      - "5434:5434"





# services:
#   agent_service:
#     build:
#       context: .
#       dockerfile: docker/Dockerfile.service
#     ports:
#       - "80:80"
#     env_file:
#       - .env
#     develop:
#       watch:
#         - path: src/agents/
#           action: sync+restart
#           target: /app/agents/
#         - path: src/schema/
#           action: sync+restart
#           target: /app/schema/
#         - path: src/service/
#           action: sync+restart
#           target: /app/service/

#   streamlit_app:
#     build:
#       context: .
#       dockerfile: docker/Dockerfile.app
#     ports:
#       - "8501:8501"
#     depends_on:
#       - agent_service
#     environment:
#       - AGENT_URL=http://agent_service
#     develop:
#       watch:
#         - path: src/client/
#           action: sync+restart
#           target: /app/client/
#         - path: src/schema/
#           action: sync+restart
#           target: /app/schema/
#         - path: src/streamlit_app.py
#           action: sync+restart
#           target: /app/streamlit_app.py


